version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: docsign_db
      MYSQL_USER: docsign_user
      MYSQL_PASSWORD: docsign_pass
    ports:
      - "5678:5678"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: